# Generated by Django 2.2.1 on 2019-05-09 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('summary', models.CharField(max_length=9999999)),
                ('published', models.CharField(max_length=255)),
                ('authors', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Scholar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('authors', models.CharField(max_length=99999)),
                ('categories', models.CharField(max_length=255)),
                ('scholar_id', models.CharField(max_length=255)),
                ('published', models.CharField(max_length=255)),
                ('summary', models.CharField(max_length=9999999)),
                ('title', models.CharField(max_length=255)),
                ('updated', models.CharField(max_length=255)),
                ('url', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Twitter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categories', models.CharField(max_length=255)),
                ('favorite_count', models.IntegerField()),
                ('hashtags', models.CharField(max_length=255)),
                ('hashtags_count', models.IntegerField()),
                ('links', models.CharField(max_length=9999)),
                ('mentions', models.CharField(max_length=255)),
                ('published', models.CharField(max_length=255)),
                ('retweet_count', models.IntegerField()),
                ('summary', models.CharField(max_length=9999999)),
                ('url', models.CharField(max_length=9999)),
                ('user_id', models.CharField(max_length=255)),
                ('user_name', models.CharField(max_length=255)),
                ('user_screen_name', models.CharField(max_length=255)),
                ('sentiment', models.CharField(max_length=255)),
                ('tweet_id', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Weibo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categories', models.CharField(max_length=255)),
                ('favorite_count', models.IntegerField()),
                ('hashtags', models.CharField(max_length=255)),
                ('hashtags_count', models.IntegerField()),
                ('links', models.CharField(max_length=255)),
                ('published', models.CharField(max_length=255)),
                ('summary', models.CharField(max_length=9999999)),
                ('url', models.CharField(max_length=255)),
                ('user_id', models.CharField(max_length=255)),
                ('user_name', models.CharField(max_length=255)),
                ('weibo_id', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Zhihu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=255)),
                ('authorUrl', models.CharField(max_length=255)),
                ('headline', models.CharField(max_length=255)),
                ('headlineUrl', models.CharField(max_length=255)),
                ('published', models.CharField(max_length=255)),
                ('summary', models.CharField(max_length=9999999)),
                ('upvotes', models.IntegerField()),
            ],
        ),
    ]
